name: "Update pull request"

on: 
  pull_request:
    types: [opened]

jobs:
  initial_comment_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Initial comment
        uses: ./.github/actions/pr-initial-comment
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
